### ISSUE TITLE
Console shows that methods are depreciated

### ISSUE THREAD

**Issue by judahb** [tiagostutz/casbin-jwt-express#3]
[node-casbin] Enforce.newModel() is deprecated, please use casbin.newModel().
[node-casbin] Enforce.newEnforcer() is deprecated, please use casbin.newEnforcer().

Depreciated symbol

**Comment by hsluoyz** [comment]
@judahb Current Casbin version used is `v1.1.5`. Updating Casbin dependency to latest `v2.0.0` will fix this issue: https://github.com/casbin/node-casbin

https://github.com/tiagostutz/casbin-jwt-express/blob/d0691287ea482c005e6e95bc9a56d8f30e6730b3/package.json#L30-L33

@tiagostutz can you help update Casbin dependency to latest version and publish a new release? Thanks.

**Comment by tiagostutz** [comment]
Sure... thanks.  
Done! `npm` updated.
